apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: default
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: kubelet
  podMonitorSelector:
    matchLabels:
      team: node-exporter
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false

#  volumeMounts:
#    - mountPath:
#      name: